/* GENERATED by script/genPrices.ts — do not edit by hand.
   The price source the Stripe Checkout Function trusts. Regenerated on every
   `npm run build`; committed so the amounts the payment path will charge are
   reviewable in a diff. */
export const PRICES = {
  "solos": {
    "sermorelin": {
      "name": "Sermorelin",
      "m1": 129,
      "m3": 116,
      "m6": 110,
      "m12": 103
    },
    "ipamorelin": {
      "name": "Ipamorelin",
      "m1": 189,
      "m3": 159,
      "m6": 161,
      "m12": 129
    },
    "cjc-1295": {
      "name": "CJC-1295 (no-DAC)",
      "m1": 239,
      "m3": 209,
      "m6": 203,
      "m12": 179
    },
    "ipa-cjc": {
      "name": "Ipamorelin / CJC-1295 Blend",
      "m1": 199,
      "m3": 179,
      "m6": 169,
      "m12": 159
    },
    "tesamorelin": {
      "name": "Tesamorelin",
      "m1": 299,
      "m3": 269,
      "m6": 254,
      "m12": 239
    },
    "selank": {
      "name": "Selank",
      "m1": 189,
      "m3": 170,
      "m6": 161,
      "m12": 151
    },
    "semax": {
      "name": "Semax",
      "m1": 189,
      "m3": 170,
      "m6": 161,
      "m12": 151
    },
    "cerebrolysin": {
      "name": "Cerebrolysin",
      "m1": 299,
      "m3": 259,
      "m6": 254,
      "m12": 229
    },
    "bpc-157": {
      "name": "BPC-157",
      "m1": 179,
      "m3": 161,
      "m6": 152,
      "m12": 143
    },
    "tb-500": {
      "name": "TB-500",
      "m1": 259,
      "m3": 233,
      "m6": 220,
      "m12": 207
    },
    "bpc-tb-combo": {
      "name": "BPC-157 + TB-500",
      "m1": 399,
      "m3": 359,
      "m6": 339,
      "m12": 319
    },
    "ghk-cu": {
      "name": "GHK-Cu",
      "m1": 129,
      "m3": 116,
      "m6": 110,
      "m12": 103
    },
    "epitalon": {
      "name": "Epitalon",
      "m1": 199,
      "m3": 179,
      "m6": 169,
      "m12": 159
    },
    "nad-plus": {
      "name": "NAD+",
      "m1": 149,
      "m3": 134,
      "m6": 127,
      "m12": 119
    },
    "mots-c": {
      "name": "MOTS-c",
      "m1": 169,
      "m3": 152,
      "m6": 144,
      "m12": 135
    },
    "semaglutide": {
      "name": "Semaglutide",
      "m1": 229,
      "m3": 206,
      "m6": 195,
      "m12": 183
    },
    "tirzepatide": {
      "name": "Tirzepatide",
      "m1": 399,
      "m3": 359,
      "m6": 339,
      "m12": 319
    },
    "dsip": {
      "name": "DSIP",
      "m1": 129,
      "m3": 116,
      "m6": 110,
      "m12": 103
    },
    "pt-141": {
      "name": "PT-141",
      "m1": 99,
      "m3": 89,
      "m6": 84,
      "m12": 79
    },
    "thymosin-a1": {
      "name": "Thymosin Alpha-1",
      "m1": 159,
      "m3": 143,
      "m6": 135,
      "m12": 127
    },
    "aod-9604": {
      "name": "AOD-9604",
      "m1": 199,
      "m3": 179,
      "m6": 169,
      "m12": 159
    },
    "oxytocin": {
      "name": "Oxytocin Nasal",
      "m1": 99,
      "m3": 89,
      "m6": 84,
      "m12": 79
    },
    "tadalafil": {
      "name": "Tadalafil Nasal",
      "m1": 89,
      "m3": 80,
      "m6": 76,
      "m12": 71
    },
    "testosterone": {
      "name": "Testosterone Cypionate",
      "m1": 149,
      "m3": 134,
      "m6": 127,
      "m12": 119
    },
    "kisspeptin": {
      "name": "Kisspeptin",
      "m1": 169,
      "m3": 152,
      "m6": 144,
      "m12": 135
    }
  },
  "stacks": {
    "recover": {
      "name": "Recovery protocol",
      "perMonth": 349
    },
    "ascend": {
      "name": "Longevity protocol",
      "perMonth": 379
    },
    "lucidity": {
      "name": "Focus and sleep protocol",
      "perMonth": 349
    },
    "ignite": {
      "name": "Weight protocol",
      "perMonth": 399
    }
  },
  "terms": {
    "1mo": {
      "months": 1,
      "label": "One month",
      "tier": "m1"
    },
    "3mo": {
      "months": 3,
      "label": "3 months",
      "tier": "m3"
    },
    "6mo": {
      "months": 6,
      "label": "6 months",
      "tier": "m6"
    },
    "12mo": {
      "months": 12,
      "label": "12 months",
      "tier": "m12"
    }
  }
} as const;
export type Prices = typeof PRICES;
