/* ═══ 1200w image variants ═══
   The photographic tiles ship a two-step srcset: 800w and 1600w. A phone at
   dpr 3 rendering a full-width tile needs ~1170 CSS pixels of image, so the
   browser correctly takes the 1600w — and the home page pulls 2.3MB before
   the reader scrolls.

   A 1200w step still EXCEEDS what that device asks for, so it costs nothing
   in quality and roughly halves the pixels (1200² / 1600² = 0.56). This is
   the reason to prefer it over capping `sizes`: capping would hand the
   device fewer pixels than it wants and soften the photography, which on
   this brand is the product.

   Rendered through Chromium's canvas, the same path the studio renders take.
   Run: node script/genImageVariants.mjs
   Idempotent: an existing -1200w.webp newer than its source is left alone. */
import { chromium } from "playwright";
import { readdir, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const DIR = "client/public/img";
const TARGET = 1200;
const MIN_SOURCE_BYTES = 90 * 1024; // only files heavy enough to be worth a step
const QUALITY = 0.82;

const files = (await readdir(DIR)).filter(
  (f) => f.endsWith(".webp") && !f.includes("-800w") && !f.includes("-1200w"),
);

const browser = await chromium.launch();
const page = await browser.newPage();
let made = 0, skipped = 0;

for (const f of files) {
  const src = join(DIR, f);
  const out = join(DIR, f.replace(/\.webp$/, "-1200w.webp"));
  const s = await stat(src);
  if (s.size < MIN_SOURCE_BYTES) { skipped++; continue; }
  if (existsSync(out) && (await stat(out)).mtimeMs > s.mtimeMs) { skipped++; continue; }

  const b64 = (await import("node:fs/promises")).readFile(src, "base64");
  const dataUrl = `data:image/webp;base64,${await b64}`;
  const result = await page.evaluate(
    async ([url, target, q]) => {
      const img = new Image();
      img.src = url;
      await img.decode();
      if (img.naturalWidth <= target) return null; // already small enough
      const scale = target / img.naturalWidth;
      const c = document.createElement("canvas");
      c.width = target;
      c.height = Math.round(img.naturalHeight * scale);
      const ctx = c.getContext("2d");
      ctx.imageSmoothingQuality = "high";
      ctx.drawImage(img, 0, 0, c.width, c.height);
      return c.toDataURL("image/webp", q);
    },
    [dataUrl, TARGET, QUALITY],
  );
  if (!result) { skipped++; continue; }
  await writeFile(out, Buffer.from(result.split(",")[1], "base64"));
  const after = (await stat(out)).size;
  console.log(`  ${f.padEnd(30)} ${Math.round(s.size / 1024)}KB → ${Math.round(after / 1024)}KB`);
  made++;
}
await browser.close();

/* Emit the manifest the client uses to decide whether a 1200w step exists
   for a given file. Referencing a variant that was never written would 404
   and, worse, would silently drop that candidate from the srcset. */
const have = (await readdir(DIR))
  .filter((f) => f.endsWith("-1200w.webp"))
  .map((f) => f.replace("-1200w.webp", ".webp"))
  .sort();
await writeFile(
  "client/src/data/imageVariants.ts",
  `/* GENERATED by script/genImageVariants.mjs — do not edit by hand.
   The public/img files that have a 1200w companion. A phone at dpr 3 asks
   for ~1170 CSS pixels on a full-width tile, so this step serves it without
   handing back the 1600w original. */
export const HAS_1200W: ReadonlySet<string> = new Set(${JSON.stringify(have, null, 2)});

/** The srcset for a public/img photo, with the 1200w step when one exists. */
export function imgSrcSet(src: string, src800?: string): string {
  const base = src.split("/").pop() ?? "";
  const steps: string[] = [];
  if (src800) steps.push(\`\${src800} 800w\`);
  if (HAS_1200W.has(base)) steps.push(\`\${src.replace(/\\.webp$/, "-1200w.webp")} 1200w\`);
  steps.push(\`\${src} 1600w\`);
  return steps.join(", ");
}
`,
  "utf8",
);
console.log(`\n${made} variants written, ${skipped} skipped, manifest: ${have.length} files`);
