/* ═══ The server-side price manifest ═══
   Writes functions/api/_prices.ts — the ONLY price source the Stripe
   Checkout Function trusts.

   Why this file exists at all: a browser that can name its own amount can
   buy a twelve-month term for a dollar. The Function therefore never reads
   a price from the request; it reads slug + term + quantity and looks the
   money up here. That makes this manifest a security boundary, not a
   convenience, so it is GENERATED from the same catalog the pages render
   rather than hand-kept beside it.

   Parsed out of the source text rather than imported, following the house
   pattern (genLlms, genSitemap): importing the data modules pulls the app's
   "@/" alias and, in the stacks' case, assets Node cannot load.

   Run as part of `npm run build`; the output is committed so a reader can
   diff what the payment path will charge. */
import { readFile, writeFile, mkdir } from "node:fs/promises";

export interface PriceManifest {
  solos: Record<string, { name: string; m1: number; m3: number; m6: number; m12: number }>;
  stacks: Record<string, { name: string; perMonth: number }>;
  terms: Record<string, { months: number; label: string; tier: "m1" | "m3" | "m6" | "m12" }>;
}

const TERMS: PriceManifest["terms"] = {
  "1mo": { months: 1, label: "One month", tier: "m1" },
  "3mo": { months: 3, label: "3 months", tier: "m3" },
  "6mo": { months: 6, label: "6 months", tier: "m6" },
  "12mo": { months: 12, label: "12 months", tier: "m12" },
};

/** Split the catalog source into one block per entry, keyed by slug. */
function blocksBySlug(src: string): Map<string, string> {
  const out = new Map<string, string>();
  const starts = [...src.matchAll(/slug:\s*"([a-z0-9-]+)"/g)];
  starts.forEach((m, i) => {
    const from = m.index ?? 0;
    const to = i + 1 < starts.length ? (starts[i + 1].index ?? src.length) : src.length;
    out.set(m[1], src.slice(from, to));
  });
  return out;
}

export async function generatePrices(root = process.cwd()): Promise<PriceManifest> {
  const soloSrc = await readFile(`${root}/client/src/data/soloCatalog.ts`, "utf-8");
  const stackSrc = await readFile(`${root}/client/src/data/stacksCatalog.ts`, "utf-8");

  const solos: PriceManifest["solos"] = {};
  for (const [slug, block] of blocksBySlug(soloSrc)) {
    const name = block.match(/name:\s*"([^"]+)"/)?.[1];
    const pricing = block.match(/pricing:\s*\{\s*m1:\s*(\d+),\s*m3:\s*(\d+),\s*m6:\s*(\d+),\s*m12:\s*(\d+)\s*\}/);
    if (!name || !pricing) continue; // consult-priced entries have no self-serve price
    solos[slug] = { name, m1: +pricing[1], m3: +pricing[2], m6: +pricing[3], m12: +pricing[4] };
  }

  /* Stacks price from `cad(<perMonth>)`, the helper the catalog uses to build
     its four cadences from one monthly figure. */
  const stacks: PriceManifest["stacks"] = {};
  for (const [slug, block] of blocksBySlug(stackSrc)) {
    const name = block.match(/name:\s*"([^"]+)"/)?.[1];
    const per = block.match(/cadences:\s*cad\((\d+)\)/)?.[1];
    if (!name || !per) continue;
    stacks[slug] = { name, perMonth: +per };
  }

  const manifest: PriceManifest = { solos, stacks, terms: TERMS };
  const body = `/* GENERATED by script/genPrices.ts — do not edit by hand.
   The price source the Stripe Checkout Function trusts. Regenerated on every
   \`npm run build\`; committed so the amounts the payment path will charge are
   reviewable in a diff. */
export const PRICES = ${JSON.stringify(manifest, null, 2)} as const;
export type Prices = typeof PRICES;
`;
  await mkdir(`${root}/functions/api`, { recursive: true });
  await writeFile(`${root}/functions/api/_prices.ts`, body, "utf-8");
  return manifest;
}
