/* ═══ SITEMAP GENERATOR ═══
   Regenerates client/public/sitemap.xml from the real data every build, so
   it can never drift again (it was hand-maintained and had silently dropped
   all 10 journal articles and all 8 goal pages). We read the data files as
   TEXT and extract slugs by anchored regex — importing the modules directly
   is impossible because journal.ts imports .webp assets Node can't load. */
import { readFile, writeFile } from "node:fs/promises";

const BASE = "https://nexphoria.com";

/** Pull the string after `slug: "` from a data source file. */
async function slugsFrom(path: string): Promise<string[]> {
  const src = await readFile(path, "utf-8");
  const out: string[] = [];
  const re = /\bslug:\s*"([a-z0-9-]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(src)) !== null) out.push(m[1]);
  return [...new Set(out)];
}

/* The 8 goal categories — the PeptideCategory union in data/peptides.ts. */
const GOAL_CATEGORIES = [
  "recovery", "skin", "cognition", "sleep",
  "growth", "longevity", "metabolic", "sexual-health",
];

/* journal.ts also declares JournalCategory slugs (foundations, protocols, …)
   with the same `slug:` shape as articles. These are NOT article routes —
   /journal/foundations would 404 — so exclude them. */
const JOURNAL_CATEGORY_SLUGS = new Set([
  "foundations", "protocols", "research", "metabolic",
  "longevity", "performance", "hormones", "safety",
]);

/* Static routes that always exist (App.tsx). Alias/redirect and
   checkout/cart/gate routes are intentionally excluded from the sitemap. */
const STATIC_ROUTES = [
  "/", "/men", "/women",
  "/about", "/science", "/physicians", "/pricing", "/bloodwork",
  "/how-it-works", "/faq", "/contact", "/community", "/booking", "/assessment",
  "/protocols", "/stacks", "/stacks/build", "/peptides", "/gift",
  "/men/peptides", "/women/peptides", "/journal",
  "/legal", "/legal/hipaa-notice", "/legal/prescribing-policy",
  "/legal/privacy", "/legal/refund-policy", "/legal/state-availability",
  "/legal/telehealth-consent", "/legal/terms",
];

export async function generateSitemap(): Promise<number> {
  const root = process.cwd();
  const solos = await slugsFrom(`${root}/client/src/data/soloCatalog.ts`);
  const stacks = await slugsFrom(`${root}/client/src/data/stacksCatalog.ts`);
  const articles = (await slugsFrom(`${root}/client/src/data/journal.ts`))
    .filter((s) => !JOURNAL_CATEGORY_SLUGS.has(s));

  const paths = new Set<string>(STATIC_ROUTES);

  // goal decision pages
  GOAL_CATEGORIES.forEach((c) => paths.add(`/goals/${c}`));

  // every solo peptide, unworlded + both worlds (all three are real routes)
  solos.forEach((s) => {
    paths.add(`/peptides/${s}`);
    paths.add(`/men/peptides/${s}`);
    paths.add(`/women/peptides/${s}`);
  });

  // flagship protocols ('build' is already a static route)
  stacks.filter((s) => s !== "build").forEach((s) => paths.add(`/stacks/${s}`));

  // journal articles
  articles.forEach((a) => paths.add(`/journal/${a}`));

  const ordered = [...paths].sort();
  const body = ordered
    .map((p) => `  <url><loc>${BASE}${p}</loc></url>`)
    .join("\n");
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by script/genSitemap.ts at build time — do not edit by hand.
     Composed from data/soloCatalog, data/stacksCatalog, data/journal, the
     8 goal categories, and the static route list. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
  await writeFile(`${root}/client/public/sitemap.xml`, xml, "utf-8");
  return ordered.length;
}

// Allow standalone invocation: `tsx script/genSitemap.ts`
if (import.meta.url === `file://${process.argv[1]}`) {
  generateSitemap()
    .then((n) => console.log(`sitemap.xml written — ${n} URLs`))
    .catch((e) => { console.error(e); process.exit(1); });
}
