/* GENERATED by script/genImageVariants.mjs — do not edit by hand.
   The public/img files that have a 1200w companion. A phone at dpr 3 asks
   for ~1170 CSS pixels on a full-width tile, so this step serves it without
   handing back the 1600w original. */
export const HAS_1200W: ReadonlySet<string> = new Set([
  "img_1217733ee45f.webp",
  "img_1b972aa3c417.webp",
  "img_1d040e499a7a.webp",
  "img_20e1e1d49da4.webp",
  "img_232f30f5a464.webp",
  "img_31d2f355633b.webp",
  "img_334cb24acfa5.webp",
  "img_3678caab4727.webp",
  "img_3a64b1f2aca5.webp",
  "img_3eae89cb98a0.webp",
  "img_40db6393468a.webp",
  "img_427d5e7427b9.webp",
  "img_44f7a8ee7f92.webp",
  "img_4f2bd889825e.webp",
  "img_5072e4db8390.webp",
  "img_56a29d462771.webp",
  "img_6bbc99ce7347.webp",
  "img_6bee78326414.webp",
  "img_6d55c7017047.webp",
  "img_72c3a0233fe1.webp",
  "img_82c3e3ceeecf.webp",
  "img_84444e0185e3.webp",
  "img_8742acc94d7e.webp",
  "img_916e52b67436.webp",
  "img_928775d1e9c1.webp",
  "img_ba067fd9f405.webp",
  "img_band_porcelain.webp",
  "img_c4bef27c5b72.webp",
  "img_ca6ddc167d62.webp",
  "img_ceff7bb26099.webp",
  "img_cf1396d09b4a.webp",
  "img_e90c14c4f953.webp",
  "img_ebd08f5a334f.webp",
  "img_f6cb022cc6fe.webp",
  "img_f8d241785924.webp",
  "img_fad0fee022a9.webp",
  "img_ff10791a8167.webp"
]);

/** The srcset for a public/img photo, with the 1200w step when one exists. */
export function imgSrcSet(src: string, src800?: string): string {
  const base = src.split("/").pop() ?? "";
  const steps: string[] = [];
  if (src800) steps.push(`${src800} 800w`);
  if (HAS_1200W.has(base)) steps.push(`${src.replace(/\.webp$/, "-1200w.webp")} 1200w`);
  steps.push(`${src} 1600w`);
  return steps.join(", ");
}
